# Generated by Django 6.0.1 on 2026-01-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_resena'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='testimonios/')),
                ('comentario', models.TextField()),
                ('red_social', models.CharField(choices=[('Instagram', 'Instagram'), ('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('TikTok', 'TikTok'), ('otro', 'Otro')], default='Instagram', max_length=50)),
                ('calificacion', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('destacado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Testimonio',
                'verbose_name_plural': 'Testimonios',
                'ordering': ['-fecha'],
            },
        ),
    ]
